application: hello-world
version:     1
runtime:     python27
api_version: 1
threadsafe:  true




handlers:

- url: /
  script: index.app




# Static asset folders

- url: /media/
  static_dir: static/media
- url: /scripts/
  static_dir: static/scripts
- url: /styles/
  static_dir: static/styles

